#ifndef __SAVE_TO_FLASH_CONFIG_H
#define __SAVE_TO_FLASH_CONFIG_H

#define FLASH_COUNTER_SECTOR_MASK		(SECTORG | SECTORF | SECTORE)
#define FLASH_COUNTER_START_ADDR		0x3DC000	// Sector G start
#define FLASH_COUNTER_END_ADDR			0x3E7FFF	// Sector E end

#endif // __SAVE_TO_FLASH_CONFIG_H
