#ifndef __SAVE_TO_FLASH_CONFIG_H
#define __SAVE_TO_FLASH_CONFIG_H

#define FLASH_DIAG_SECTOR_MASK			SECTORG
#define FLASH_DIAG_START_ADDR			0x3DC000	// Sector G start
#define FLASH_DIAG_END_ADDR				0x3DFFFF	// Sector G end

#define FLASH_COUNTER_SECTOR_MASK		(SECTORF | SECTORE)
#define FLASH_COUNTER_START_ADDR		0x3E0000	// Sector F start
#define FLASH_COUNTER_END_ADDR			0x3E7FFF	// Sector E end

#endif // __SAVE_TO_FLASH_CONFIG_H
